### ISSUE TITLE
Actualización de la página

### ISSUE THREAD

**Issue by carlosgruiz-dev** [pyve/pyve.github.io#130]
Este Issue sirve para agrupar todas las mejoras necesarias para actualizar la página web de Python Venezuela durante el 2do semestre de 2017. Algunas tareas:

- Corregir la configuración del dominio
- Actualizar la url de Telegram
- Cerrar Issues y PR en el Repositorio
- Revisar Contenidos
- (otros que agreguen en los comentarios)

**Comment by jackboot7** [comment]
El tema del dominio se notificó, sin respuesta, el 7 de Abril de este año en este [hilo de la lista](https://groups.google.com/forum/?hl=es#!searchin/python-venezuela/Domain$27s$20DNS$20record$20could$20not$20be$20retrieved.$20For$20more$20information$2C$20see%7Csort:relevance/python-venezuela/D7DKGhrznP0/WtyiGxulBAAJ)

Ese caso específico se trataba de los urls que redireccionaban a Github de manera usual (python.info.ve, creo que era uno)

@nhomar  ¿Puedes echarle un ojo a esto?

**Comment by jgomo3** [comment]
Propongo otro punto: Cambiar el sistema de publicación.

Creo que el proceso de publicación basado en páginas estáticas y un flujo de trabajo basado en git conllevan un costo que no promueve la generación de contenidos de la misma manera que otros sistemas de gestión de contenidos más dinámicos.

Estoy hablando de Plone, Odoo, Wordpress, Drupal, MediaWiki, etc...

**Comment by atmantree** [comment]
@jackboot7 en efecto, lo recuerdo.. si, la idea es recopilar todas las tareas pendientes y nuevas ideas a ver si les caemos en cayapa en este 2do semeste.

**Comment by atmantree** [comment]
@jgomo3 concuerdo contigo, sin embargo podríamos dejar el sitio en lektor con algunos cambios y promover contenido importando artículos propios a un grupo (o como se llame) en Medium. Ver ejemplo de [ngVenezuela](https://medium.com/ngvenezuela).

**Comment by jackboot7** [comment]
@jgomo3  En lo personal no me molesta la página "promocional" sea llevada con lektor, ya que es eso, una página promocional, no un blog. Sí podríamos, como sugiere @atmantree, enlazar a medium o cualquier plataforma donde se agregue contenido más dinámico tipo blog.

La mayoría aquí tenemos blogs personales, no estaría mal buscar la manera de hacer un "planet" (muy early 2000's ??) que reúna todos estos blogs/publicaciones.

**Comment by jgomo3** [comment]
@jackboot7 Tienes razón.

Y ahora que lo mencionas, tal vez sea bueno hacer un blog de PyVe para registrar anecdotas de eventos y hechos importantes de la comunidad.

**Comment by jackboot7** [comment]
@jgomo3 El problema con "abrir un blog" para llevar registro "oficial" de eventos y hechos importantes es el mismo que hemos tenido en todo: **¿quién se ocupa?**

Me suena más práctico buscar la manera de condensar todos los artículos de la comunidad, capaz una receta de ITTT sirva para eso.

**Comment by jgomo3** [comment]
@jackboot7 claro pana. Pero ese es un problema propio del blog mismo.

No digo que sean excluyentes las ideas. Por un lado el _planet_ y por otro el _blog_.

**Comment by atmantree** [comment]
@jackboot7 @jgomo3 medium tiene una opción para importar artículos (ver https://medium.com/p/import). No es en vivo como el plantet pero así los autores solo se suben los artículos relacionados con Python Venezuela y pueden escribir sobre cualquier otro tema en sus blogs.

**Comment by jackboot7** [comment]
Otro punto, de los 25 issues pendientes, deberíamos hacer una lista de prioridades.

**Comment by atmantree** [comment]
@jackboot7 concuerdo, donde hacemos la lista? un gdocs, un gist? tu la armas?

**Comment by hernanramirez** [comment]
Hace tiempo un grupo de PyVe @flaper87 @hernanramirez et at habíamos tropicalizado la pagina python.org Creo que el repo esta por aqui.. si mal no recuerdo esta hecha con django.

Quizas podamos retomar ese projecto.

**Comment by atmantree** [comment]
@hernanramirez en mi opinión es cosa de contemplar la viabilidad de mantener una plataforma así, porque todos andamos bastante atareados y es posible que no podamos dedicarle mucho tiempo. En todo caso es cosa de realizar la consulta a ver si se incorporan nuevos colaboradores.

**Comment by atmantree** [comment]
listado de tickets abiertos (wip, tuve que salir pero lo completo en un rato)

https://github.com/pyve/pyve.github.io/wiki/Issues-Pendientes

**Comment by jackboot7** [comment]
Gracias @atmantree 

Hice unas pequeñas ediciones sobre el listado.
