### ISSUE TITLE
Desarrollo de software

### ISSUE THREAD

**Issue by cp1n7o** [pyve/pyve.github.io#131]
Saludos a todos en la comunidad,quisiera contar con su apoyo en el desarrollo de un software de administración para estacionamientos, el software tendrá varias etapas y la primera es el desarrollo de las funciones básicas de cobranza,calculo del tiempo de estadía deun vehiculo, se pueden comunicar conmigo a carloshpinto@outlook.com   o también a cp1n7o@gmail.com

**Comment by atmantree** [comment]
@cp1n7o comunícate al grupo de Python Venezuela por su lista de correos (http://pyve.github.io/lista-de-correos/) o por su chat de Telegram (https://t.me/python_venezuela), allí podremos ayudarte.

Cierro el issue porque los de este repositorio son dedicados a solventar problemas en la página web.
