### ISSUE TITLE
Crear página para proyectos

### ISSUE THREAD

**Issue by satanas** [pyve/pyve.github.io#75]
Muchos de nosotros tenemos proyectos que no están en el repo de github de pyve, así que sería bueno crear una página donde podamos enlazarlos todos y además enlazar el repo de github de pyve

**Comment by atmantree** [comment]
:+1: 
iniciamos un markdown en la wiki para hacer ese inventario?

**Comment by jgomo3** [comment]
@atmantree: ¿Cuál es la intención del Wiki? Dejar lo que propone @satanas ahí, o usar el Wiki como taller para luego pasar eso a la página?.

**Comment by atmantree** [comment]
Es para hacer un censo, nada muy estructurado pero que pueda ser utilizado así mismo o pasado otro sitio más pertinente.

Sent from my Fire

On February 6, 2016, at 16:23, Jesús Gómez <notifications@github.com> wrote:

@atmantree: ¿Cuál es la intención del Wiki? Dejar lo que propone @satanas ahí, o usar el Wiki como taller para luego pasar eso a la página?.

**Comment by jgomo3** [comment]
¿Entonces damos este issue por cerrado? Es decir ¿consideramos que el wiki satisface la petición?

**Comment by atmantree** [comment]
Creo que satisface la petición, luego se abre otro ticket para moverla a donde corresponda.

Sent from my Fire

On February 7, 2016, at 22:41, Jesús Gómez <notifications@github.com> wrote:

¿Entonces damos este issue por cerrado? Es decir ¿consideramos que el wiki satisface la petición?
